Traceback (most recent call last):
  File "/Users/danhammer/streamlitenv/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/danhammer/streamlitenv/lib/python3.7/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/danhammer/streamlitenv/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/danhammer/streamlitenv/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/Users/danhammer/streamlitenv/lib/python3.7/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/danhammer/streamlitenv/lib/python3.7/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/danhammer/streamlitenv/lib/python3.7/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
operating = df[df.status == "Operating"]
operating.groupby("coalType")["annualCarbon"].sum()
hist_data = operating.groupby("regionLabel")["annualCarbon"].sum()
hist_data = hist_data.reset_index().sort_values("annualCarbon")
plt.barh(hist_data.regionLabel, hist_data.annualCarbon)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-10-ebb789067a48>[0m in [0;36m<module>[0;34m[0m
[1;32m      3[0m [0mhist_data[0m [0;34m=[0m [0moperating[0m[0;34m.[0m[0mgroupby[0m[0;34m([0m[0;34m"regionLabel"[0m[0;34m)[0m[0;34m[[0m[0;34m"annualCarbon"[0m[0;34m][0m[0;34m.[0m[0msum[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mhist_data[0m [0;34m=[0m [0mhist_data[0m[0;34m.[0m[0mreset_index[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0msort_values[0m[0;34m([0m[0;34m"annualCarbon"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 5[0;31m [0mplt[0m[0;34m.[0m[0mbarh[0m[0;34m([0m[0mhist_data[0m[0;34m.[0m[0mregionLabel[0m[0;34m,[0m [0mhist_data[0m[0;34m.[0m[0mannualCarbon[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'plt' is not defined
NameError: name 'plt' is not defined

